export const categories = [
  "Fiction",
  "Non-Fiction",
  "Children's Books",
  "Young Adult",
  "Classics",
  "Comics & Graphic Novels",
  "Science & Technology",
  "Biographies & Memoirs",
  "Travel",
  "Cookbooks",
  "History",
  "Arts & Photography",
  "Self-help",
  "Education",
  "Politics & Social Sciences",
  "Business & Economics",
  "Religion & Spirituality",
  "Health & Fitness",
  "Crime & Thriller",
  "Romance",
  "Sci-Fi & Fantasy",
  "Sports",
  "Music",
  "Law",
  "Gardening",
  "Pets & Animal Care"
]

export const productCategories = [
  {
    name: "Fiction",
    subcategories: [
      { name: "Literary", icon: "https://placehold.co/50" },
      { name: "Mystery & Thriller", icon: "https://placehold.co/50" },
      { name: "Historical", icon: "https://placehold.co/50" },
      { name: "Romance", icon: "https://placehold.co/50" },
      { name: "Science Fiction", icon: "https://placehold.co/50" },
      { name: "Fantasy", icon: "https://placehold.co/50" },
      { name: "Horror", icon: "https://placehold.co/50" },
      { name: "Western", icon: "https://placehold.co/50" },
      { name: "Dystopian", icon: "https://placehold.co/50" },
      { name: "Magical Realism", icon: "https://placehold.co/50" },
      { name: "Graphic Novels", icon: "https://placehold.co/50" },
    ],
  },
  {
    name: "Non-Fiction",
    subcategories: [
      { name: "History", icon: "https://placehold.co/50" },
      { name: "Biographies", icon: "https://placehold.co/50" },
      { name: "Science & Technology", icon: "https://placehold.co/50" },
      { name: "Psychology", icon: "https://placehold.co/50" },
      { name: "Self-help", icon: "https://placehold.co/50" },
      { name: "Travel", icon: "https://placehold.co/50" },
      { name: "Cookbooks", icon: "https://placehold.co/50" },
      { name: "True Crime", icon: "https://placehold.co/50" },
      { name: "Health & Fitness", icon: "https://placehold.co/50" },
      { name: "Arts & Photography", icon: "https://placehold.co/50" },
      { name: "Memoirs", icon: "https://placehold.co/50" },
      { name: "Education", icon: "https://placehold.co/50" },
      { name: "Business & Economics", icon: "https://placehold.co/50" },
      { name: "Law & Politics", icon: "https://placehold.co/50" },
    ],
  },
  {
    name: "Children's Books",
    subcategories: [
      { name: "Picture Books", icon: "https://placehold.co/50" },
      { name: "Early Learning", icon: "https://placehold.co/50" },
      { name: "Chapter Books", icon: "https://placehold.co/50" },
      { name: "Interactive Books", icon: "https://placehold.co/50" },
      { name: "Educational Books", icon: "https://placehold.co/50" },
      { name: "Animal Stories", icon: "https://placehold.co/50" },
      { name: "Fantasy & Adventure", icon: "https://placehold.co/50" },
      { name: "Historical Fiction", icon: "https://placehold.co/50" },
    ],
  },
]